play:
  # Description of the service
  description: Play youtube keyword.
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name(s) of the entities to set
      # Example value that can be passed for this field
      example: 'media_player.speaker'
    key_word:
      description: Key word to search and play.
      example: "Từng yêu"