play:
  # Description of the service
  description: Play ZingMP3 top 100.
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name(s) of the entities to set
      # Example value that can be passed for this field
      example: 'media_player.speaker'
    music_type:
      description: 'List music_type: Pop, Country, Rock, Dance, R&B, Rap, Soundtrack, Nhac tre, Tru tinh, Que huong, Cach mang, Rock Viet, Rap Viet, Dance Viet'
      example: 'Nhac tre'
    repeat:
      description: "optional, default: 'off'"
      example: 'off'
    shuffle: 
      description: "optional, default: 'off'"
      example: 'on'
